### ISSUE TITLE
Problem with Tornado 5.0.0

### ISSUE THREAD

**Issue by louisabraham** [miyakogi/wdom#3]
Traceback (most recent call last):
      File "/var/folders/ns/bvd4v4bd62jg8qvwyn02dtdh0000gn/T/pythonInTerm.mibZh4sR", line 1, in <module>
        from wdom.document import get_document
      File "/Users/louisabraham/miniconda3/lib/python3.6/site-packages/wdom/document.py", line 17, in <module>
        from wdom import server
      File "/Users/louisabraham/miniconda3/lib/python3.6/site-packages/wdom/server/__init__.py", line 17, in <module>
        from wdom.server import _tornado as module
      File "/Users/louisabraham/miniconda3/lib/python3.6/site-packages/wdom/server/_tornado.py", line 22, in <module>
        install_asyncio()
      File "/Users/louisabraham/miniconda3/lib/python3.6/site-packages/wdom/util.py", line 36, in install_asyncio
        if not IOLoop.initialized():
    AttributeError: type object 'IOLoop' has no attribute 'initialized'

**Comment by louisabraham** [comment]
My bad, this is solved in the development version.
Great code, I learn a lot from the project organization by the way.

**Comment by miyakogi** [comment]
Sorry, I forget to upload new version to PyPI.
Now fixed version is available on PyPI.
